phrasal_verbs = [
    {"english": "ask out", "portuguese": "convidar para sair"},
    {"english": "bring up", "portuguese": "mencionar"},
    {"english": "call back", "portuguese": "ligar de volta"},
    {"english": "call off", "portuguese": "cancelar"},
    {"english": "call up", "portuguese": "ligar para alguém"},
    {"english": "check out", "portuguese": ["verificar, conferir"]},
    {"english": "come back", "portuguese": "voltar"},
    {"english": "come in", "portuguese": "entrar"},
    {"english": "come over", "portuguese": "visitar"},
    {"english": "come up", "portuguese": "surgir"},
    {"english": "cut off", "portuguese": ["cortar, interromper"]},
    {"english": "do over", "portuguese": "fazer de novo"},
    {"english": "drop off", "portuguese": ["deixar, largar"]},
    {"english": "figure out", "portuguese": ["compreender, resolver"]},
    {"english": "find out", "portuguese": "descobrir"},
    {"english": "get along", "portuguese": "dar-se bem"},
    {"english": "get away", "portuguese": "escapar"},
    {"english": "get back", "portuguese": "voltar"},
    {"english": "get off", "portuguese": "descer"},
    {"english": "get on", "portuguese": "subir"},
    {"english": "get up", "portuguese": "levantar-se"},
    {"english": "give away", "portuguese": ["dar, doar"]},
    {"english": "give in", "portuguese": ["ceder, desistir"]},
    {"english": "give back", "portuguese": "devolver"},
    {"english": "give up", "portuguese": "desistir"},
    {"english": "go away", "portuguese": "ir embora"},
    {"english": "go back", "portuguese": "voltar"},
    {"english": "go on", "portuguese": "continuar"},
    {"english": "go out", "portuguese": "sair"},
    {"english": "grow up", "portuguese": "crescer"},
    {"english": "hang out", "portuguese": ["passar tempo, sair"]},
    {"english": "hang up", "portuguese": "desligar"},
    {"english": "hold on", "portuguese":["aguardar, segurar firme"]},
    {"english": "keep on", "portuguese": "continuar"},
    {"english": "let down", "portuguese": "decepcionar"},
    {"english": "look after", "portuguese": "cuidar de"},
    {"english": "look for", "portuguese": "procurar"},
    {"english": "look forward to", "portuguese": "ansiar por"},
    {"english": "look out", "portuguese": "ter cuidado"},
    {"english": "look up", "portuguese": ["pesquisar, melhorar"]},
    {"english": "make out", "portuguese": "entender"},
    {"english": "make up", "portuguese": ["inventar, fazer as pazes"]},
    {"english": "pick up", "portuguese": ["pegar, buscar"]},
    {"english": "put away", "portuguese": "guardar"},
    {"english": "put off", "portuguese": "adiar"},
    {"english": "put on", "portuguese": ["vestir, colocar"]},
    {"english": "put out", "portuguese": "apagar"},
    {"english": "put up with", "portuguese": ["tolerar, suportar"]},
    {"english": "run into", "portuguese": "encontrar por acaso"},
    {"english": "run over", "portuguese": ["atropelar, revisar rapidamente"]},
    {"english": "run out of", "portuguese": "ficar sem"},
    {"english": "set up", "portuguese": ["configurar, montar"]},
    {"english": "set off", "portuguese": ["partir, iniciar uma jornada"] },
    {"english": "show up", "portuguese": "aparecer"},
    {"english": "shut up", "portuguese": "calar-se"},
    {"english": "take after", "portuguese": "puxar a alguém"},
    {"english": "take away", "portuguese": "levar embora"},
    {"english": "take back", "portuguese": "devolver"},
    {"english": "take off", "portuguese": ["decolar, tirar a roupa"]},
    {"english": "take out", "portuguese": ["tirar, levar para sair"]},
    {"english": "take over", "portuguese": "assumir o controle"},
    {"english": "take up", "portuguese": "começar um hobby"},
    {"english": "throw away", "portuguese": "jogar fora"},
    {"english": "try on", "portuguese": "experimentar roupa"},
    {"english": "turn down", "portuguese": ["recusar, abaixar volume"]},
    {"english": "turn off", "portuguese": "desligar"},
    {"english": "turn on", "portuguese": "ligar"},
    {"english": "turn up", "portuguese": ["aparecer, aumentar volume"]},
    {"english": "wake up", "portuguese": "acordar"},
    {"english": "warm up", "portuguese": "aquecer"},
    {"english": "watch out", "portuguese": "prestar atenção"},
    {"english": "work out", "portuguese": ["exercitar-se, resolver"]},
    {"english": "write down", "portuguese": "anotar"},
    {"english": "break down", "portuguese": "quebrar"},
    {"english": "break up", "portuguese": "terminar um relacionamento"},
    {"english": "bring back", "portuguese": "trazer de volta"},
    {"english": "bring in", "portuguese": "trazer, introduzir"},
    {"english": "bring out", "portuguese": "lançar, revelar"},
    {"english": "bring over", "portuguese": "trazer alguém"},
    {"english": "bring together", "portuguese": "juntar"},
    {"english": "bring up", "portuguese": "mencionar"},
    {"english": "carry on", "portuguese": "continuar"},
    {"english": "carry out", "portuguese": ["realizar, executar"]},
    {"english": "come across", "portuguese": "encontrar por acaso"},
    {"english": "come along", "portuguese": "acompanhar, chegar"},
    {"english": "come apart", "portuguese": ["desmanchar, separar"]},
    {"english": "come down", "portuguese": "descer"},
    {"english": "come out", "portuguese": ["sair, revelar-se"]},
    {"english": "come over", "portuguese": "visitar"},
    {"english": "come through", "portuguese":["passar por, sobreviver"] },
    {"english": "come up with", "portuguese": ["sugerir, propor"]},
    {"english": "cut back", "portuguese": "reduzir"},
    {"english": "cut down", "portuguese": "reduzir"},
    {"english": "cut in", "portuguese": "interromper"},
    {"english": "cut out", "portuguese": "cortar, excluir"},
    {"english": "drop by", "portuguese": "dar uma passada"},
    {"english": "drop out", "portuguese": "abandonar"},
    {"english": "fall apart", "portuguese": "desmoronar"},
    {"english": "fall down", "portuguese": "cair"},
    {"english": "fall for", "portuguese": ["apaixonar-se, cair em uma mentira"]},
    {"english": "fall off", "portuguese": "cair de"},
    {"english": "fall over", "portuguese": "tropeçar e cair"},
]